<?php

namespace Locals\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends EntityRepository
{
}
